### ISSUE TITLE
Can't find real touch device.

### ISSUE THREAD

**Issue by laiqun** [kp7742/TouchSimulation#1]
I have two similar devices, but event2 is real touch device.
Add getevent log:
add device 4: /dev/input/event5
  bus:      0000
  vendor    0000
  product   0001
  version   0007
  name:     "synaptics_tcm_touch"
  location: "synaptics_tcm/touch_input"
  id:       ""
  version:  1.0.1
  events:
    KEY (0001): KEY_WAKEUP            BTN_TOOL_FINGER       BTN_TOUCH            
    ABS (0003): ABS_X                 : value 0, min 0, max 1619, fuzz 0, flat 0, resolution 0
                ABS_Y                 : value 0, min 0, max 3599, fuzz 0, flat 0, resolution 0
                ABS_MT_SLOT           : value 0, min 0, max 9, fuzz 0, flat 0, resolution 0
                ABS_MT_POSITION_X     : value 0, min 0, max 1619, fuzz 0, flat 0, resolution 0
                ABS_MT_POSITION_Y     : value 0, min 0, max 3599, fuzz 0, flat 0, resolution 0
                ABS_MT_TRACKING_ID    : value 0, min 0, max 65535, fuzz 0, flat 0, resolution 0
  input props:
    INPUT_PROP_DIRECT

add device 7: /dev/input/event2
  bus:      0000
  vendor    0000
  product   0000
  version   0000
  name:     "vivo_ts"
  location: ""
  id:       ""
  version:  1.0.1
  events:
    KEY (0001): KEY_W                 KEY_E                 KEY_O                 KEY_A                
                KEY_F                 KEY_H                 KEY_C                 KEY_V                
                KEY_M                 KEY_UP                KEY_LEFT              KEY_RIGHT            
                KEY_MENU              KEY_WAKEUP            KEY_BACK              KEY_HOMEPAGE         
                KEY_CAMERA            00f9                  00fa                  00fe                 
                BTN_TOOL_FINGER       BTN_TOUCH             025d                  KEY_PRIVACY_SCREEN_T      
                0280                  02f2                  02f3                  02f4                 
                02f5                  02f6                  02f7                  02f8                 
    ABS (0003): ABS_MT_SLOT           : value 0, min 0, max 9, fuzz 0, flat 0, resolution 0
                ABS_MT_TOUCH_MAJOR    : value 0, min 0, max 31, fuzz 0, flat 0, resolution 0
                ABS_MT_TOUCH_MINOR    : value 0, min 0, max 31, fuzz 0, flat 0, resolution 0
                ABS_MT_POSITION_X     : value 0, min 0, max 1619, fuzz 0, flat 0, resolution 0
                ABS_MT_POSITION_Y     : value 0, min 0, max 3599, fuzz 0, flat 0, resolution 0
                ABS_MT_TRACKING_ID    : value 0, min 0, max 65535, fuzz 0, flat 0, resolution 0
  input props:
    INPUT_PROP_DIRECT

**Comment by kp7742** [comment]
is event5 the Side action button like for firing?

**Comment by laiqun** [comment]
it event2~

**Comment by kp7742** [comment]
Then it is correct, Because program should emulate touch screen and not action button.
